#!/bin/sh
# The Sway configuration file in ~/.config/sway/config calls this script.

# Produces "21 days", for example
uptime_formatted=$(uptime | cut -d ',' -f1  | cut -d ' ' -f4,5)

# The abbreviated weekday (e.g., "Sat"), followed by the ISO-formatted date
# like 2018-10-06 and the time (e.g., 14:01)
date_formatted=$(date "+%a %F %H:%M")

# Returns the battery status: "Full", "Discharging", or "Charging".
battery_status=$(cat /sys/class/power_supply/BAT0/status)
battery_percentage=$(acpi | cut -d',' -f2)

ssid=$(iw wlp58s0 info | grep ssid | sed 's/ssid //')


# Get volume information for the Master channel. 
master_right=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 " (" $4 ")" }')
master_left=$(amixer sget Master | grep 'Left:' |   awk -F'[][]' '{ print $2 " (" $4 ")" }')
master='!!!'

# If both channel are the same, only display one.
if [[ "$master_left" == "$master_right" ]]; then
	master="$master_left"
else
	master="$master_left\|$master_right"
fi	


# If there is no ssid, replace the string with disconnected.
# If there is a tunnel interface running, bracket the ssid. 
if [ -z ${ssid} ]; then
    ssid="*disconnected*"
else 
	signal_strength=$(awk 'NR==3 {printf( "%.0f%", $3*10/7 )}' /proc/net/wireless)
	if ip addr | grep -q 'tun0:'; then
		ssid="<<<$ssid>>>"
	fi
	ssid+=" - $signal_strength"
fi
    
echo $uptime_formatted '||' $ssid '||' $battery_status $battery_percentage '||' $master '||' $date_formatted
