#!/bin/sh
# The Sway configuration file in ~/.config/sway/config calls this script.
# You should see changes to the status bar after saving this script.
# If not, do "killall swaybar" and $mod+Shift+c to reload the configuration.

# Produces "21 days", for example
uptime_formatted=$(uptime | cut -d ',' -f1  | cut -d ' ' -f4,5)

# The abbreviated weekday (e.g., "Sat"), followed by the ISO-formatted date
# like 2018-10-06 and the time (e.g., 14:01)
date_formatted=$(date "+%a %F %H:%M")

# Returns the battery status: "Full", "Discharging", or "Charging".
battery_status=$(cat /sys/class/power_supply/BAT0/status)
battery_percentage=$(acpi | cut -d',' -f2)

ssid=$(iw wlp58s0 info | grep ssid | cut -d' ' -f2)

if [ -z ${ssid} ]; then
    ssid=*disconnected*
elif ip addr | grep -q 'tun0:'; then
    ssid+=" => VPN"
fi
    
echo $uptime_formatted '||' $ssid '||' $battery_status $battery_percentage '||' $date_formatted
