#!/bin/bash

function raise_error {
	local error_message="$@"
    echo "${error_message}" 1>&2;
}

function print_usage {
	echo "Usage: buff up|down|status"
}

function try_link { 
	if [ ! -f ~/$2 ]; then
		ln -v -s `pwd`/$1 ~/$2
	else 
		echo "File ${2} already exists: skipping..."
	fi
}


arg=$1

case $arg in
	vim)
		try_link vim/vimrc .vimrc
                try_link etc/aspell.en.pws .vim/spell/en.utf-8.add
		;;
	zsh)
		try_link zsh/zshrc.sh .zshrc
		try_link zsh/keybindings.sh .keybindings
		try_link zsh/zsh_exports.sh .zsh_exports
		try_link zsh/zsh-dircolors.config .zsh-dircolors.config
		;;
	emacs)
		try_link emacs/emacs.el .emacs.el
		try_link emacs/sbclrc .sbclrc
		try_link emacs/eshell/alias .emacs.d/eshell/alias
		try_link emacs/eshell/commands.el .emacs.d/eshell/commands.el
                try_link etc/aspell.en.prepl .aspell.en.prepl
                try_link etc/aspell.en.pws .aspell.en.pws
		;;
	screen)
		try_link etc/screenrc .screenrc
		;;
	bash)
		try_link bash/bash_profile.sh .bash_profile
		try_link bash/bashrc.sh .bashrc
		try_link bash/bash_aliases.sh .bash_aliases
		;;
	xorg)
		try_link xorg/xinitrc .xinitrc
		try_link xorg/Xresources .Xresources
		;;
	sway)
		try_link wayland/Xdefaults .Xdefaults
		try_link wayland/sway.config .config/sway/config
		try_link wayland/swaybar .config/sway/swaybar
		try_link wayland/termite.config .config/termite/config
		;;
	termite)
		try_link wayland/termite.config .config/termite/config
		;;
	tmux)
		try_link tmux/tmux.conf .tmux.conf
		;;
	xmonad)
		try_link xmonad/xmonad.hs .xmonad/xmonad.hs
		;;
	git)
		try_link etc/gitconfig .gitconfig
		;;
	rtorrent)
		try_link etc/rtorrent.rc .rtorrent.rc
		;;
        imap)
            try_link mail/offlineimaprc .offlineimaprc
            try_link mail/offlineimap.py .offlineimap.py
            ;;
	ycmd)
		try_link etc/ycm_extra_conf.py .ycm_extra_conf.py
		;;
	vifm)
	    try_link etc/vifmrc .vifm/vifmrc
            	;;
	*)
		raise_error
		print_usage
		;;
esac
